name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-45
      options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Flatpak bundle
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
        with:
          bundle: io.github.starnight.gtkdemo.flatpak
          manifest-path: build-aux/flatpak/io.github.starnight.gtkdemo.yml
          cache: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          cache-key: flatpak-builder-${{ github.sha }}
